# ----------------------------------#
#           Week 02--Day04          #
# Scatter Plot (Association) Review #
#     Bar Graph (Frequency/Amount)  #
#-----------------------------------#

#==============================================#
# Part 2: Visualizing Association between Two  #
#         Quantitative Variables--Scatter Plot #
#    (Fundamentals of dataVis: Chapter 12)     #
#==============================================#

library(tidyverse)
head(diamonds)
ggplot() + 
  geom_point(aes(x=table, y=price), data=diamonds) + 
  scale_color_manual(values = c("red","blue", "yellow", "purple","green")) +
  labs(x="Table", y="Price") +
  ggtitle("Scatterplot between price and table") +
  theme(plot.title = element_text(hjust=0.5)) +
  theme(legend.position = "bottom")
  
  # If you want to assign colors to all points:
  # constant color(outside aes()) or
  # assign color by variable (inside aes()) or
  # scale_color_manual is used to define color by ourselves
  #

  # THINGS TO MAKE IT PRETTY:
  #   Legend Position
  #   Color of points
  #   Labels of Arises
  #   Title
  #   



#==================================================#
# Part 3: Visualizing Frequency/Amount--Bar graph  #
#       (Fundamentals of dataVis: Chapter 6)       #
#==================================================#

### (3.1) Visualizing frequency ###
## (1) Bar Graph Intro
head(diamonds)

## What should we do with the "clarity" variable?
# It is qualitative: descriptions of groups or things. 
# Recall ordinal/nominal variables in day02
# Refer to: https://www.statisticshowto.com/quantitative-variables-data/
#    or at: https://online.stat.psu.edu/stat200/lesson/1/1.1/1.1.1

## Count how many dimonds are there in each type of "clarity".
## See an example of bargraph in https://www.mathsisfun.com/data/bar-graphs.html
## Make a bargraph with "geom_bar"

?geom_bar
ggplot() +
  geom_bar(aes(x=clarity), data=diamonds)


# You can just specify what variable you're interested with. 
# geom_bar will display the groups in the x axis and y is the
# frequency of the group.



## (2) Work with summarized data
## Question: How is the bargraph made?
## Do I have other ways to create the same graph?
tables(diamonds$clarity)
clarity_df <- data.frame(table(diamonds$clarity))
str(clarity_df)
clarity_df



ggplot() +
  geom_bar(aes(x=Var1), data=clarity_df)



## a. Using the "geom_col"
ggplot() +
  geom_col(aes(x=Var1, y=Freq), data=clarity_df)



## b. Directly use "geom_bar"
# You can specify the "identity" option in "geom_bar".
# Since here, you're telling R which is the variable you're interested with, which
# is the value you want to display.
ggplot() +
  geom_bar(aes(x=Var1, y=Freq), data=clarity_df, stat="identity") +
  labs(x="Clarity", y="Frequency") +
  ggtitle("Bar Graph of Clarity") +
  theme(plot.title = element_text(hjust = 0.5))

## (3) Want to display the bars horizontally?




### (3.2) Visualizing amount ###

## (1) Through "stat_summary"
# Summarize y values at unique/binned x

# Question: Visualize the mean price for each type of cut?
ggplot() +
  stat_summary(aes(x=cut,y=price),fun="mean", data=diamonds,geom="bar")

mean(diamonds[diamonds$cut=="Fair","price", drop=TRUE])

# Question: Visualize the median price per clarity type?
ggplot() +
  stat_summary(aes(x=clarity,y=price),fun="median", data=diamonds,geom="bar")

# More details, refer to: https://ggplot2.tidyverse.org/reference/stat_summary.html


## (2) Create the summary data first, then plot

# The pipe, %>%, comes from the magrittr package (the aim of the package is to
# decrease development time and to improve readability and maintainability 
# of code) You can pronounce the symbol  %>% as "then". 
# Behind the scenes, x %>% f(y) turns into f(x, y), 
# and x %>% f(y) %>% g(z) turns into g(f(x, y), z) and so on. 

# "group_by": group the data according to one/more variables 
# grouping doesn't change how the data looks (apart from listing how it's grouped):
diamonds2 <- diamonds %>% group_by(clarity)

clarity_summary <-diamonds2 %>% summarise(clarity.mean=mean(price),
                                          clarity.median=median(price),
                                          n=n())
clarity_summary




#compare the data
clarity_df
clarity_summary

# compare the graphs
# graph generated by "stat_summary"
ggplot() +
  stat_summary(aes(x=cut,y=price),fun="mean", data=diamonds,geom="bar")


# graph with the new data
ggplot() +
  geom_bar(aes(clarity,y=clarity.mean), data=clarity_summary, stat="identity")



#IC03
# 1
median(diamonds[diamonds$cut=="Fair","price", drop=TRUE])
median(diamonds[diamonds$cut=="Good","price", drop=TRUE])
median(diamonds[diamonds$cut=="Very Good","price", drop=TRUE])
median(diamonds[diamonds$cut=="Premium","price", drop=TRUE])
median(diamonds[diamonds$cut=="Ideal","price", drop=TRUE])

# 2
medianPriceByCut <- diamonds %>% group_by(cut) %>% summarise(clarity.median=median(price))
medianPriceByCut
